name: Invoke sql failback
on: workflow_dispatch
jobs:  
  job1:
    permissions:
      contents: none
    runs-on: ubuntu-latest       
    steps:
    - name: checkout
      uses: actions/checkout@v2 
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_Deloitte}}
        enable-AzPSSession: true   
    - name: Invoke sql back
      uses: azure/powershell@v1
      with:
        inlineScript: |
          ./Invoke_SQL_Failback_param.ps1 -primary_mssql_server_resource_group_name "${{vars.PRIMARY_MSSQL_SERVER_RESOURCE_GROUP_NAME}}" -primary_mssql_server_name "${{vars.PRIMARY_MSSQL_SERVER_NAME_1}}" -failover_group_name "${{vars.FAILOVER_GROUP_NAME_1}}" -primary_mssql_server_subscription_Id "${{vars.PRIMARY_MSSQL_SERVER_SUBSCRIPTION_ID}}"
          ./Invoke_SQL_Failback_param.ps1 -primary_mssql_server_resource_group_name "${{vars.PRIMARY_MSSQL_SERVER_RESOURCE_GROUP_NAME}}" -primary_mssql_server_name "${{vars.PRIMARY_MSSQL_SERVER_NAME_2}}" -failover_group_name "${{vars.FAILOVER_GROUP_NAME_2}}" -primary_mssql_server_subscription_Id "${{vars.PRIMARY_MSSQL_SERVER_SUBSCRIPTION_ID}}"
        azPSVersion: "latest"
